name: Publish Unit Test Results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_run:
    workflows: ["Build and run tests"]
    types:
      - completed

jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
           echo "jalla"
